import { camelCase, kebabCase } from '../../utils';
import { FileGenerator, Question, QuestionType } from '../../definitions';

export interface GeneratorFileGenerator extends FileGenerator {
    generatorName: string
}

export const kaapiGeneratorGenerator: GeneratorFileGenerator = {
    name: 'kaapi-generator',
    type: 'others',
    description: 'Creates a simple generator for kaapi.',
    options: {
        name: 'The name of the generator'
    },

    generatorName: '',

    init: function (options: Record<string, unknown>): void {
        if (typeof options['name'] == 'string') {
            this.generatorName = camelCase(options['name'])
        }
    },
    getFileContent: function (): string {
        let className = camelCase(this.generatorName);
        className = className.substring(0, 1).toUpperCase() + className.substring(1)
        const cmdName = kebabCase(this.generatorName)
        return `import { FileGenerator, FileGeneratorType, Question, QuestionType } from '@kaapi/cli/definitions'
import { kebabCase } from '@kaapi/cli/utils'

export class ${className} implements FileGenerator {
    get type(): FileGeneratorType {
        return 'others'
    }

    get name(): '${cmdName}' {
        return '${cmdName}'
    }

    get description(): string {
        return 'Creates a simple app starter.'
    }

    get notes(): string[] {
        return []
    }

    get options(): Record<string, string> {
        return {
            name: 'The name of the app.'
        }
    }

    private _values = {
        name: ''
    }

    init(options: Record<string, unknown>): void {
        if (typeof options['name'] == 'string') {
            this._values.name = options['name']
        }
    }

    isValid(): boolean {
        return true
    }

    getQuestions(): Question[] {
        return [
            {
                type: QuestionType.text,
                options: {
                    message: 'What is the name of the app?',
                    defaultValue: 'app',
                    placeholder: 'app'
                },
                setValue: (value) => {
                    this._values.name = \`\${value}\`
                },
                skip: () => !!this._values.name
            }
        ]
    }

    getFilename(): string {
        return \`\${kebabCase(this._values.name)}.ts\`
    }

    getFileContent(): string {
        return \` // generated by ${cmdName}

import { Kaapi } from '@kaapi/kaapi';

const app = new Kaapi({
    port: 3000,
    host: 'localhost',
    docs: {
        title: '\${this._values.name}',
        host: {
            url: process.env.EXTERNAL_URI || '',
        }
    }
});

const start = async () => {

    await app.listen();

    const BASE_URI = process.env.EXTERNAL_URI || app.base().info.uri;

    app.log(\\\`Server running on \\\${BASE_URI}\\\n\\\`);
    app.log(\\\`Swagger UI on \\\${BASE_URI}/docs/api\\\`);
    app.log(\\\`OpenAPI specification on \\\${BASE_URI}/docs/api/schema\\\`);
    app.log(\\\`Postman collection on \\\${BASE_URI}/docs/api/schema?format=postman\\\`);
};

process.on('unhandledRejection', (err) => {
    console.log(err);
    process.exit(1);
});

start();
        \`
    }
}
`
    },
    isValid(): boolean {
        return !!this.generatorName
    },
    getQuestions(): Question[] {
        return [
            {
                type: QuestionType.text,
                options: {
                    message: 'The name of the generator?',
                    defaultValue: 'custom-generator',
                    placeholder: 'custom-generator'
                },
                setValue: (generatorName) => {
                    this.generatorName = camelCase(generatorName)
                },
                skip: () => !!this.generatorName
            }
        ]
    },
    getFilename(): string {
        return `${kebabCase(this.generatorName)}.ts`
    }
}