import { FileGenerator, FileGeneratorType, Question, QuestionType } from '@kaapi/cli/dist/definitions'
import { kebabCase } from '@kaapi/cli/dist/utils'

export class EsmAppLauncher implements FileGenerator {
    get type(): FileGeneratorType {
        return 'others'
    }

    get name(): 'esm-app-launcher' {
        return 'esm-app-launcher'
    }

    get description(): string {
        return 'Creates a simple app starter.'
    }

    get notes(): string[] {
        return []
    }

    get options(): Record<string, string> {
        return {
            name: 'The name of the app.'
        }
    }

    private _values = {
        name: ''
    }

    init(options: Record<string, unknown>): void {
        if (typeof options['name'] == 'string') {
            this._values.name = options['name']
        }
    }

    isValid(): boolean {
        return true
    }

    getQuestions(): Question[] {
        return [
            {
                type: QuestionType.text,
                options: {
                    message: 'What is the name of the app?',
                    defaultValue: 'app',
                    placeholder: 'app'
                },
                setValue: (value) => {
                    this._values.name = `${value}`
                },
                skip: () => !!this._values.name
            }
        ]
    }

    getFilename(): string {
        return `${kebabCase(this._values.name)}.ts`
    }

    getFileContent(): string {
        return ` // generated by esm-app-launcher

import { Kaapi } from '@kaapi/kaapi';

const app = new Kaapi({
    port: 3000,
    host: 'localhost',
    docs: {
        title: '${this._values.name}',
        host: {
            url: process.env.EXTERNAL_URI || '',
        }
    }
});

const start = async () => {

    await app.listen();

    const BASE_URI = process.env.EXTERNAL_URI || app.base().info.uri;

    app.log(\`Server running on \${BASE_URI}\
\`);
    app.log(\`Swagger UI on \${BASE_URI}/docs/api\`);
    app.log(\`OpenAPI specification on \${BASE_URI}/docs/api/schema\`);
    app.log(\`Postman collection on \${BASE_URI}/docs/api/schema?format=postman\`);
};

process.on('unhandledRejection', (err) => {
    console.log(err);
    process.exit(1);
});

start();
        `
    }
}
