import { FileGenerator, FileGeneratorType, Question, QuestionType } from '@kaapi/cli/definitions'
import { camelCase, kebabCase } from '@kaapi/cli/utils'

const FLOW_OPTIONS = [
    {
        value: 'oidc-auth-code',
        label: 'OIDC Authorization Code',
        hint: ''
    },
    {
        value: 'oidc-client-credentials',
        label: 'OIDC Client Credentials',
        hint: ''
    },
    {
        value: 'oidc-device-flow',
        label: 'OIDC Device Flow',
        hint: ''
    }
];

export class OAuth2FileGenerator implements FileGenerator {

    get type(): FileGeneratorType {
        return 'auth-design'
    }

    get name(): 'oauth2-generator' {
        return 'oauth2-generator'
    }

    get description(): string {
        return 'Creates an auth design based on OAuth2 specifications.'
    }

    get notes(): string[] {
        return [
            'Allowed values for --flow:',
            ...FLOW_OPTIONS.map(o => `  - ${o.value}`)
        ]
    }

    get options(): Record<string, string> {
        return {
            name: 'The name of the auth design',
            flow: 'The grant type flow'
        }
    }

    #values = {
        name: '',
        flow: ''
    }

    init(options: Record<string, unknown>): void {
        if (typeof options['name'] == 'string') {
            this.#values.name = camelCase(options['name'])
        }
        if (typeof options['flow'] == 'string') {
            if (!FLOW_OPTIONS.map(v => v.value).includes(options['flow'])) {
                throw new Error(`Invalid value for '--flow'. Allowed values are: ${FLOW_OPTIONS.map(v => v.value).join(', ')}.`)
            }
            this.#values.flow = options['flow']
        }
    }

    isValid(): boolean {
        return !!this.#values.name
    }

    getFileContent(): string {
        return `// generated by @kaapi/oauth2-auth-design

import {
    BearerToken,
    OIDCAuthorizationCodeBuilder,
    createInMemoryKeyStore,
    createMatchAuthCodeResult,
    OAuth2TokenResponse,
    ClientSecretBasic,
    ClientSecretPost,
    NoneAuthMethod,
    OAuth2ErrorCode,
} from '@kaapi/oauth2-auth-design';

const VALID_CLIENTS = [
    {
        client_id: 'service-api-client',
        client_secret: 's3cr3tK3y123!',
        allowed_scopes: ['openid', 'profile', 'email', 'read', 'write'],
    },
];

const REGISTERED_USERS = [{ id: 'user-1234', username: 'user', password: 'password', email: 'user@email.com' }];

const authCodesStore: Map<
    string,
    { clientId: string; scopes: string[]; userId: string; codeChallenge?: string | undefined }
> = new Map();

export const oidcAuthCodeBuilder = OIDCAuthorizationCodeBuilder.create()
    // the name of the strategy
    .strategyName('${kebabCase(this.#values.name)}')
    // access token TTL (used in generateToken controller)
    .setTokenTTL(3600)
    // activate auto parsing of access token (jwtAccessTokenPayload + createJwtAccessToken)
    .useAccessTokenJwks(true)
    // Client authentication methods
    .addClientAuthenticationMethod(new ClientSecretBasic())
    .addClientAuthenticationMethod(new ClientSecretPost())
    .addClientAuthenticationMethod(new NoneAuthMethod())
    .setTokenType(new BearerToken())
    // Define scopes
    .setScopes({
        profile: 'Access to basic profile information such as name and picture.',
        email: "Access to the user's email address and its verification status.",
        read: 'Grants read-only access to protected resources',
        write: 'Grants write access to protected resources',
    })

    // Authorization
    .authorizationRoute<object, { Payload: { username?: string; password?: string } }>((route) =>
        route
            .setPath('/oauth2/v1.0/authorize')
            .setUsernameField('username')
            .setPasswordField('password')
            // only validate one client id (dev)
            .setClientId(VALID_CLIENTS[0].client_id)
            .generateCode(async ({ clientId, codeChallenge, scope }, req, _h) => {
                // client exists?
                const client = VALID_CLIENTS.find((c) => c.client_id === clientId);
                if (!client) return null;

                // filter client's allowed scoped
                const requestedScopes = (scope ?? '').split(/\\s+/).filter(Boolean);
                const grantedScopes = requestedScopes.length
                    ? requestedScopes.filter((s) => client.allowed_scopes.includes(s))
                    : client.allowed_scopes;
                if (grantedScopes.length === 0) return null;

                // user exists?
                const user = REGISTERED_USERS.find(
                    (u) => u.username === req.payload.username && u.password === req.payload.password
                );
                if (!user) return null;

                // generate code
                const code = \`auth-${Date.now()}\`;
                authCodesStore.set(code, { clientId, scopes: grantedScopes, userId: user.id, codeChallenge });
                return { type: 'code', value: code };
            })
            .finalizeAuthorization(async (ctx, _params, _req, h) => {
                // redirect to callback url (could do something else depending on the code result)
                const matcher = createMatchAuthCodeResult({
                    code: async () => h.redirect(ctx.fullRedirectUri),
                    continue: async () => h.redirect(ctx.fullRedirectUri),
                    deny: async () => h.redirect(ctx.fullRedirectUri),
                });
                return matcher(ctx.authorizationResult);
            })
    )

    // Token exchange
    .tokenRoute((route) =>
        route.generateToken(
            async ({
                clientId,
                ttl,
                tokenType,
                code,
                clientSecret,
                codeVerifier,
                createJwtAccessToken,
                createIdToken,
                verifyCodeVerifier,
            }) => {
                const entry = authCodesStore.get(code);
                if (!entry || entry.clientId !== clientId) return null;

                const client = VALID_CLIENTS.find((c) => c.client_id === clientId);
                if (!client) {
                    return {
                        error: OAuth2ErrorCode.INVALID_CLIENT,
                        error_description: 'Client authentication failed.',
                    };
                }

                if (entry.codeChallenge && codeVerifier) {
                    if (!verifyCodeVerifier(codeVerifier, entry.codeChallenge)) {
                        return {
                            error: OAuth2ErrorCode.INVALID_GRANT,
                            error_description: 'Invalid authorization grant.',
                        };
                    }
                } else if (clientSecret) {
                    if (client.client_secret !== clientSecret) {
                        return {
                            error: OAuth2ErrorCode.INVALID_CLIENT,
                            error_description: 'Client authentication failed.',
                        };
                    }
                } else {
                    return {
                        error: OAuth2ErrorCode.INVALID_REQUEST,
                        error_description: 'Missing or invalid request parameter.',
                    };
                }

                const user = REGISTERED_USERS.find((u) => u.id === entry.userId);
                if (!user) {
                    return {
                        error: OAuth2ErrorCode.INVALID_GRANT,
                        error_description: 'Invalid authorization grant.',
                    };
                }

                // Generate a signed JWT access token
                const { token: accessToken } = await createJwtAccessToken!({
                    sub: entry.userId,
                    client_id: clientId,
                    scope: entry.scopes,
                });

                // Generate a signed JWT id token
                const idToken = entry.scopes.includes('openid')
                    ? (await createIdToken!({ sub: entry.userId, name: user.username, aud: clientId })).token
                    : undefined;

                // Return token response
                return new OAuth2TokenResponse({ access_token: accessToken })
                    .setExpiresIn(ttl)
                    .setTokenType(tokenType)
                    .setScope(entry.scopes)
                    .setIdToken(idToken);
            }
        )
    )

    // Access Token Validation
    .validate(async (_req, { jwtAccessTokenPayload }) => {
        if (!jwtAccessTokenPayload?.sub) return { isValid: false };
        return {
            isValid: true,
            credentials: {
                user: {
                    id: jwtAccessTokenPayload.sub,
                    clientId: jwtAccessTokenPayload.client_id,
                },
                scope: Array.isArray(jwtAccessTokenPayload.scope) ? jwtAccessTokenPayload.scope : [],
            },
        };
    })
        
    // JWKS
    .jwksRoute((route) => route.setPath('/discovery/v1.0/keys')) // activates jwks uri
    .setPublicKeyExpiry(86400) // 24h
    .setJwksKeyStore(createInMemoryKeyStore()) // store for JWKS
    .setJwksRotatorOptions({
        intervalMs: 7.884e9, // 91 days
        timestampStore: createInMemoryKeyStore(),
    });
`
    }

    getQuestions(): Question[] {
        const r: Question[] = []

        if (!this.#values.name) {
            r.push({
                type: QuestionType.text,
                options: {
                    message: 'The name of the auth design?',
                    defaultValue: 'oauth2AuthDesign',
                    placeholder: 'oauth2AuthDesign'
                },
                setValue: (pluginName) => {
                    this.#values.name = camelCase(pluginName)
                }
            })
        }

        if (!(this.#values.flow && FLOW_OPTIONS.map(v => v.value).includes(this.#values.flow))) {
            r.push({
                type: QuestionType.select,
                options: {
                    message: 'The authorization flow?',
                    options: FLOW_OPTIONS,
                    initialValue: 'oidc-auth-code'
                },
                setValue: (value) => {
                    this.#values.flow = `${value}`
                }
            })
        }

        return r
    }

    getFilename(): string {
        return kebabCase(`${this.#values.name}`) + '.ts'
    }
}